#!/usr/bin/perl

use strict;
use Test::Mock::Apache2;

#*CORE::GLOBAL::die = sub { require Carp; Carp::confess(); };
#$SIG{__WARN__} = sub { require Carp; Carp::confess(); };

use ComposerCat::Search qw(index_all_pages);

sub main {
    index_all_pages;
}

main;
