#!/usr/bin/perl

use strict;

#*CORE::GLOBAL::die = sub { require Carp; Carp::confess(); };
#$SIG{__WARN__} = sub { require Carp; Carp::confess(); };

use ComposerCat::Ingestion qw(create_workbook);
use ComposerCat::Database qw(all_records);

sub main {
    my $filename = create_workbook(all_records);

}

main;
