#!/usr/bin/perl

use strict;

*CORE::GLOBAL::die = sub { require Carp; Carp::confess(); };
$SIG{__WARN__} = sub { require Carp; Carp::confess(); };

use Getopt::Std;
use PrOCAV::Ingestion qw(ingest_workbook);

# Command line options should be
#   -i   input spreadshet
my %options = ();
getopts("i:x:", \%options);

sub main {
    if (exists $options{i}) {
	ingest_workbook($options{i}, split(/\,/, $options{x}));
    } else {
	die "No filename supplied.\n";
    }
}

main;
